### PR TITLE
Add CFD-online to domain specific list

### PR DESCRIPTION
**Pull request by uekerman**

### CODE REVIEW

**Comment by jspaaks** [comment]
Hi Benjamin,
thanks for your Pull Request. I'm a little bit reluctant to merge though, because the link points to a generic CFD page, not a software registry page. Even if we update the link to point to https://www.cfd-online.com/Tools/ I'm still reluctant, because that page has no metadata and the links there all point to services, meaning I can't see the software. Probably still useful, but not within the scope of this awesomelist.

Maybe as a alternative, we could use https://www.cfd-online.com/Links/soft.html ? Still no metadata but at least visitors have access to copies of the listed software.

**Comment by uekerman** [comment]
A better solution could be to link to https://www.cfd-online.com/Links/soft.html and https://www.cfd-online.com/Links/programming.html in two separate entries. What about that?
I admit that I also don't fully understand the sorting on CFD-online, but it's still a very relevant page for CFD despite its age and engineering software is currently still a bit underrepresented in this awesomelist.

**Comment by jspaaks** [comment]
ok something like 

```
* Computationla Fluid Dynamics
  * https://www.cfd-online.com/Links/soft.html
  * https://www.cfd-online.com/Links/programming.html
```
could work. 

If you can suggest descriptions for each, that'd be grand. I guess there's some overlap between the two but I guess it is what it is.

**Comment by jspaaks** [comment]
Thanks Benjamin!

**Pull request merged**
